export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const UPDATE_CUSTOMERS = "UPDATE_CUSTOMERS";
export const INSERT_CUSTOMERS = "INSERT_CUSTOMERS";
export const DELETE_CUSTOMERS = "DELETE_CUSTOMERS";
